DEPRECATED_TARGETS := ecotone-scalar receipt-reference-builder test op-deployer fuzz sync-standard-version

include ../justfiles/deprecated.mk

celo-migrate:
	go build -o ./bin/celo-migrate ./cmd/celo-migrate/*.go
