import { Hash, Hex, Log, TransactionType } from "viem";
import { Config } from "./setup";

interface WithdrawArgs {
    gas: bigint;
    to: Hex;
    amount: bigint;
  }

  interface TransactionReceipt {
    gasUsed: bigint;
    effectiveGasPrice: bigint;
    l1Fee: bigint;
    status: any;
    blobGasPrice?: bigint | undefined
    /** The amount of blob gas used. Only specified for blob transactions as defined by EIP-4844. */
    blobGasUsed?: bigint | undefined
    /** Hash of block containing this transaction */
    blockHash: Hash
    /** Number of block containing this transaction */
    blockNumber: bigint
    /** Address of new contract or `null` if no contract was created */
    contractAddress: Hex
    /** Gas used by this and all preceding transactions in this block */
    cumulativeGasUsed: bigint
    /** Pre-London, it is equal to the transaction's gasPrice. Post-London, it is equal to the actual gas price paid for inclusion. */
    /** Transaction sender */
    from: Hex
    /** Gas used by this transaction */
    /** List of log objects generated by this transaction */
    logs: Log<bigint, number, false>[]
    /** Logs bloom filter */
    logsBloom: Hex
    /** The post-transaction state root. Only specified for transactions included before the Byzantium upgrade. */
    root?: Hash | undefined
    /** `success` if this transaction was successful or `reverted` if it failed */
    /** Transaction recipient or `null` if deploying a contract */
    to: Hex | null
    /** Hash of this transaction */
    transactionHash: Hash
    /** Index of this transaction in the block */
    transactionIndex: number
    /** Transaction type */
    type: TransactionType

  }

  interface WithdrawResult {
    success: boolean;
    l2GasPayment: bigint;
  }

  // Replace 'any' with your actual config type when available
  export const withdraw = async function(
    args: WithdrawArgs,
    config: Config
  ): Promise<WithdrawResult> {
    const initiateHash = await config.client.l2.wallet.initiateWithdrawal({
      request: {
        gas: args.gas,
        to: args.to,
        value: args.amount,
      },
    });

    const receipt = await config.client.l2.public.waitForTransactionReceipt({
      hash: initiateHash,
    });
    console.log('receipt', receipt);

    const l2GasPayment = receipt.gasUsed * receipt.effectiveGasPrice + receipt.l1Fee!;

    // Wait for the receipt to be proven on L1
    const { output, withdrawal } = await config.client.l1.public.waitToProve({
      receipt,
      targetChain: config.client.l2.public.chain,
    });

    const proveWithdrawalArgs = await config.client.l2.public.buildProveWithdrawal({
      output,
      withdrawal,
    });

    const proveHash = await config.client.l1.wallet.proveWithdrawal({
        ...proveWithdrawalArgs,
      });

    const proveReceipt = await config.client.l1.public.waitForTransactionReceipt({
      hash: proveHash,
    });

    if (proveReceipt.status !== 'success') {
      return {
        success: false,
        l2GasPayment: l2GasPayment,
      };
    }

    await config.client.l1.public.waitToFinalize({
      withdrawalHash: withdrawal.withdrawalHash,
      targetChain: config.client.l2.public.chain,
    });

    // Hardcoded wait due to potential issue with waitToFinalize timing
    await new Promise<void>((resolve) => setTimeout(resolve, 16 * 1000));

    const finalizeHash = await config.client.l1.wallet.finalizeWithdrawal({
      targetChain: config.client.l2.public.chain,
      withdrawal,
    });

    const finalizeReceipt = await config.client.l1.public.waitForTransactionReceipt({
      hash: finalizeHash,
    });

    return {
      success: finalizeReceipt.status === 'success',
      l2GasPayment: l2GasPayment,
    };
  };
